### PR TITLE
Created new library which connects AKKA-HTTP with SWAGGER

### PR DESCRIPTION
**Pull request by javdom-tecsisa**

### CODE REVIEW

**Comment by javdom-tecsisa** [comment]
Done by error.

**Comment by mhamrah** [comment]
I'd be open to this MR. There's demand for it (#61).

**Comment by ugoenyioha** [comment]
Hi there. Please could you let me know how to you use this library with Akka-Http?...I'm having some trouble adapting to it from the normal spray-swagger methods. See gist for my failing attempt....

https://gist.github.com/ugoenyioha/32eef2c299dc5d31f90c

**Comment by uenyioha** [comment]
Hi there. Please could you let me know how to you use this library with Akka-Http?...I'm having some trouble adapting to it from the normal spray-swagger methods. See gist for my failing attempt....

https://gist.github.com/ugoenyioha/32eef2c299dc5d31f90c

**Pull request closed without merging**
